accounts/urls.py
from django.urls import path
from  . import views
from .views import ProcurementUpdateView, ProcurementCreateView, ProcurementDeleteView, introView, PendingUpdateView
#from .views import NewRequestCreateView 
from django.conf import settings
from django.conf.urls.static import static 

app_name = 'accounts'


urlpatterns = [
    path('', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('upload/', views.upload, name='upload'),
    path('intro/', views.introView.as_view(), name='intro'),
    path('list', views.ProcurementList.as_view(), name ='list'),
    path('complete', views.CompleteList.as_view(), name ='complete'),
    path('<int:pk>', views.ProcurementDetail.as_view(), name = 'details'),
    path('new/', views.ProcurementCreateView.as_view(), name='new'),
    path('request/', views.PendingList.as_view(), name='request'),
    path('reports', views.reports, name='reports'),
    path('chart', views.charts, name='chart'),
    path('<int:pk>/update/', views.PendingUpdateView.as_view(), name='pending_update'),
    path('<int:pk>/edit/', views.ProcurementUpdateView.as_view(), name='procurement_edit'),
    path('<int:pk>/delete/', views.ProcurementDeleteView.as_view(), name='procurement_delete'),


] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls'))
]

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2' ]

class ProcurementForm(forms.ModelForm):
    class Meta:
        model = Procurement
        fields = '__all__'

class NewRequestForm(forms.ModelForm):
    class Meta:
        model = Procurement
        fields = ['Equipment', 'PONo','Delivery_Terms', 'Budget','PPMP_Date','PPMP_Signatures',
                    'PPMP_Pages','PPMP_Days','PPMP_Attachment', 'Requested_By','Requested_Date','Types_of_Procurement', 
                    'Status', 'Document_Location', 'Comments']

accounts/views.py
import csv, io
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import *
from .models import Procurement
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from .forms import CreateUserForm, ProcurementForm, NewRequestForm
from django.http import HttpResponse
from django.views.generic.edit import UpdateView 
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.files.storage import FileSystemStorage
from .filters import ProcurementFilter
from django.db.models import Count, Avg

# Create your views here.

def registerPage(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user  )
            return redirect('accounts:login')
    context = {'form': form}
    return render(request, 'register.html', context)

def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('accounts:intro')
        else:
            messages.info(request, 'Username or Password is incorrect')
    context = {}
    return render(request, 'login.html', context)

def logoutUSer(request):
    logout(request)
    return redirect('accounts:login')

@permission_required('admin.can_add_log_entry')
def upload(request):
    template = 'upload.html'

    prompt = {
        'order': 'Upload, Procurement Dataset:'
    }
    if request.method == 'GET':
        return render(request, template, prompt)

    csv_file = request.FILES['file']
    
    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'Please upload only csv file')
    
    data_set = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(data_set)
    next(io_string)
    for column in csv.reader(io_string, quotechar='|'):
        _, created = Procurement.objects.update_or_create(
            Equipment= column[0],
            PONo= column[1],
            Delivery_Terms = column[2],
            Budget = column[3],
            PPMP_Date = column[4],
            PPMP_Signatures = column[5],
            PPMP_Pages = column[6],
            PPMP_Days = column[7],
            PR_Date = column[8],
            PR_Signatures = column[9],
            PR_Pages = column[10],
            PR_Days = column[11],
            Pre_Bid_Date = column[12],
            Pre_Bid_Signatures = column[13],
            Pre_Bid_Pages = column[14],
            Pre_Bid_Days =column[15],
            Opening_Bid_Date = column[16],
            Opening_Bid_Signatures = column[17],
            Opening_Bid_Pages = column[18],
            Opening_Bid_Days = column[19],
            Post_Qual_Date = column[20],
            Post_Qual_Signatures = column[21],
            Post_Qual_Pages = column[22],
            Post_Qual_Days = column[23],
            NOA_Date = column[24],
            NOA_Signatures = column[25],
            NOA_Pages = column[26],
            NOA_Days = column[27],
            PO_Date = column[28],
            PO_Signatures = column[29],
            PO_Pages = column[30],
            PO_Days = column[31],
            PO_Approval_Date = column[32],
            PO_Approval_Signatures = column[33],
            PO_Approval_Pages = column[34],
            PO_Approval_Days = column[35],
            PO_Supplier_Date = column[36],
            PO_Supplier_Signatures = column[37],
            PO_Supplier_Pages = column[38],
            PO_Supplier_Days = column[39],
            Delivery_Date = column[40],
            Delivery_Signatures = column[41],
            Delivery_Pages = column[42],
            Delivery_Days = column[43],
            DV_Processing_Date = column[44],
            DV_Signatures = column[45],
            DV_Pages = column[46],
            DV_Days = column[47],
            DV_Approval_Date = column[48],
            DV_Approval_Signatures = column[49],
            DV_Approval_Pages = column[50],
            DV_Approval_Days = column[51],
            OR_CR_Request_Date = column[52],
            OR_CR_Signatures = column[53],
            OR_CR_Pages = column[54],
            OR_CR_Days = column[55],
            Check_Releasing_Date = column[56],
            Check_Signatures = column[57],
            Check_Pages = column[58],
            Check_Days = column[59],
            Total_LeadTime = column[60],
            Total_Signatures = column[61],
        )
    context = {}
    return redirect('accounts:list')

class ProcurementList(ListView):
    template_name = 'list.html'
    model = Procurement

class CompleteList(ListView):
    template_name = 'complete.html'
    model = Procurement
    procurement = Procurement.objects.all()
    pending = Procurement.objects.filter(Status='Pending').count()
    ongoing = Procurement.objects.filter(Status='Approved').count()
    complete = Procurement.objects.filter(Status='Completed').count()
    #total_days = Procurement.objects.all().aggregate(Avg('Total_LeadTime'))
    #myFilter = ProcurementFilter(request.GET, queryset=procurement)
    #procurement= myFilter.qs
    #success_url = reverse_lazy('accounts:reports', context)
    #context = {'procurement':procurement, 'pending':pending, 'ongoing':ongoing, 'complete':complete}
    #return render(request, 'reports.html', context)

class ProcurementDetail(DetailView):
    context_object_name = 'obj'
    template_name = 'details.html'
    model = Procurement

class ProcurementCreateView(CreateView):
    form_class = NewRequestForm
    template_name = 'new.html'
    queryset = NewRequestForm
    success_url = reverse_lazy('accounts:')

class ProcurementUpdateView(UpdateView):  
    form_class = ProcurementForm
    template_name = 'update.html'
    queryset = ProcurementForm
    success_url = reverse_lazy('accounts:list')

    def get_object(self):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Procurement, pk=pk)

class ProcurementDeleteView(DeleteView):
    template_name = "delete.html"
    success_url = reverse_lazy('accounts:list')

    def get_object(self):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Procurement, pk=pk)

class introView(TemplateView):
    template_name = "intro.html"
    success_url = reverse_lazy('accounts:intro')

class PendingList(ListView):
    template_name = 'request.html'
    model = Procurement

class PendingUpdateView(UpdateView):  
    form_class = NewRequestForm
    template_name = 'update.html'
    queryset = NewRequestForm
    success_url = reverse_lazy('accounts:list')

    def get_object(self):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Procurement, pk=pk)


def reports(request):
    procurement = Procurement.objects.all()
    pending = Procurement.objects.filter(Status='Pending').count()
    ongoing = Procurement.objects.filter(Status='On-Going').count()
    complete = Procurement.objects.filter(Status='Completed').count()
    Purchase_Order = Procurement.objects.filter(Types_of_Procurement='Purchase-Order').count()
    Special_Procurement = Procurement.objects.filter(Types_of_Procurement='Repeat-Order').count()
    Above1M = Procurement.objects.filter(Types_of_Procurement='Bidding-1M-and-Above').count()
    Less1M = Procurement.objects.filter(Types_of_Procurement='Bidding-Less-Than-1M').count()
    Direct = Procurement.objects.filter(Types_of_Procurement='Direct-Contracting').count()
    context = {'procurement':procurement, 'pending':pending, 'ongoing':ongoing, 'complete':complete,
    'Direct':Direct, 'Purchase_Order':Purchase_Order, 'Special_Procurement':Special_Procurement, 
    'Above1M':Above1M, 'Less1M':Less1M}
    return render(request, 'reports.html', context)

def charts(request):
    context= {}
    return render(request, 'chart.html', context)

   


accounts/templates/complete.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- DATATABLE -->
    {% load static %}
    <script src="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css"/></script>
    <script src="https://cdn.datatables.net/colreorder/1.5.2/css/colReorder.dataTables.min.css"/></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/css/datatables.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap-table.min.css' %}"/>
    <title>Procurement List View</title>
  </head>
  <body>
  {%  include 'navbar.html' %}
  <br>
    <div><h2 align="justify">Completed Projects</h2></div><br>
    <div><a href="{% url 'accounts:chart' %}"><button type="button" class="btn btn-success">View Procurement Performance</button></a>&nbsp;</div>
    <div class = "container-fluid">
     <table id="example" class="table table-striped table-hover table-sm" style="width:100%">
      <thead class="thead-dark">
        <tr>
           <th><font size="4">PO No.</font></th>
          <th><font size="4">Project Name/Item</font></th>
          <th><font size="4">Approved Budget</font></th>
          <th><font size="4">Types of Procurement</font></th>
          <th><font size="4">Supplier's Name</font></th>
          <th><font size="4">Start Date</font></th>
          <th><font size="4">End Date:</font></th>
          <th><font size="4">Total Lead Time</font></th>
          <th></th>
        </tr>
      <tbody>
          {% for x in procurement_list %}
          {% if x.Status == "Completed" %}
          <tr>
               <td>{{ x.PONo}}</td>
              <td>{{ x.Equipment }}</td>
              <td>PHP. {{ x.Budget }}</td>
              <td>{{ x.Types_of_Procurement }}</td>
              <td>{{x.Supplier_Name }}</td>
              <td>{{x.PR_Date}}</td>
              <td>{{ x.Check_Releasing_Date}}</td>
              <td>{{ x.Total_LeadTime}}</td>

              <td>
                <a href='{{x.id}}'>
                    <button type="button" class="btn btn-primary">View Details</button>
                </a>&nbsp; 
                <a href="{% url 'accounts:procurement_edit' x.id %}">
                    <button type="button" class="btn btn-success">Edit</button>
                </a>
              </td>
              
          </tr>      

          {% endif %}
          {% endfor %}
      </tbody>  
    </table>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.js"/></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"/></script>
    <script src="https://cdn.datatables.net/colreorder/1.5.2/js/dataTables.colReorder.min.js"/></script>
    <script src="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css"/></script>
    <script src="https://cdn.datatables.net/colreorder/1.5.2/css/colReorder.dataTables.min.css"/></script>
    <!-- DATATABLE -->  
    <!-- DATATABLE -->
    
    <script>
     $(document).ready(function() {
            // Setup - add a text input to each footer cell
            $('#example tfoot th').each( function (i) {
                var title = $('#example thead th').eq( $(this).index() ).text();
                $(this).html( '<input type="text" placeholder="Search '+title+'" data-index="'+i+'" />' );
            } );
        
            // DataTable
            var table = $('#example').DataTable( {
                scrollY:        "300px",
                scrollX:        true,
                scrollCollapse: true,
                paging:         false,
                fixedColumns:   true
            } );
        
            // Filter event handler
            $( table.table().container() ).on( 'keyup', 'tfoot input', function () {
                table
                    .column( $(this).data('index') )
                    .search( this.value )
                    .draw();
            } );
        } );
    </script>
    <scrip>
        <script type="text/javascript">
        $(function () {
            var chartitle= {
                text: 'Monthly Average Performance of Procurement System',
                x: -20 //center
            }
            var chartsubtitle = {
                text: 'Source: UP-Diliman-College-of-Science',
                x: -20
            }
            var chartxaxis =  {
                categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
            }
            var chartyaxis = {
                title: {
                    text: 'Number of Request'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            }
            var chartooltip =  {
                valueSuffix: 'items'
            }
            var chartlegend= {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            }
            var chartseries=[{
                name: 'Pending',
                data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
            }, {
                name: 'On-Going',
                data: [-0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5]
            },  {
                name: 'Completed',
                data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
            }]
            $('#container').highcharts({
                title: chartitle,
                subtitle: chartsubtitle,
                xAxis:chartxaxis,
                yAxis: chartyaxis,
                tooltip: chartooltip,
                legend: chartlegend,
                series: chartseries
            });
        });
    </script>
    </scrip>
  </body>
</html>

accounts/templates/delete.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- DATATABLE -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/css/datatables.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap-table.min.css' %}"/>
    <title>Procurement List View</title>
  </head>
  <body>
        {%  include 'navbar.html' %}
        <div>
        <form method="post">{% csrf_token %}
            <h3>Are you sure you want to delete "</h3> {{ object }}" ?<br>
            <p><input type="submit" value="Delete" /> <a href="../">Cancel</a></p>
        </form>
        </div>
    </body>
</html>

accounts/templates/navbar.html
{% load static %}


<style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
 <img src="{% static 'images/logo.png' %}" width="100" height="100">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      {% if request.user.is_staff %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:intro' %}">Manual</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:upload' %}">Upload Dataset</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:new' %}">Add New Item</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:request' %}">Pending Requests</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:list' %}">On-Going Requests</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:complete' %}">Completed Transactions</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:reports' %}">Reports</a>
      </li>
      {% endif %}
    </ul>
  </div>

  <span class="hello-msg">Hello, {{request.user}}</span>
  <span ><a  class="hello-msg" href="{% url 'accounts:login' %}">Logout</a></span>

</nav>

accounts/templates/request.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- DATATABLE -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/css/datatables.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap-table.min.css' %}"/>
    <title>Procurement List View</title>
  </head>
  <body>
  {%  include 'navbar.html' %}
  <br>
    <div><h1>Pending Requests</h1><div><br>
    <div class = "container-fluid">
      <table id="example" class="display responsive nowrap" style="width:100%">
      <thead>
        <tr>
          <th><font size="4">PO No.</font></th>
          <th><font size="4">Project Name/Item</font></th>
          <th><font size="4">Approved Budget</font></th>
          <th><font size="4">Requested By</font></th>
          <th><font size="4">Requested Date</font></th>
          <th><font size="4">Types of Procurement</font></th>
          <th><font size="4">Status</font></th>
          <th><font size="4">Comments</font></th>
           <th><font size="4">Processed By</font></th>
          <th></th>
        </tr>
      <tbody>
          {% for x in procurement_list %}
          {% if x.Status == "New_Request"%}
            <tr>
              <td>{{ x.PONo}}</td>
              <td>{{ x.Equipment }}</td>
              <td>PHP. {{ x.Budget }}</td>
              <td>{{ x.Requested_By}}</td>
              <td>{{ x.Requested_Date}}</td>
              <td>{{ x.Types_of_Procurement}}</td>
              <td>{{ x.Status}}</td>
              <td>{{ x.Comments}}</td>
              <td>{{ x.Processed_By}}</td>

              <td>
                {% if x.PPMP_Attachment %}
                    <a class="btn btn-primary"  href="{{x.PPMP_Attachment.url}}"  target="_blank">Review PPMP</a>
                {% endif %}
                <a href="{% url 'accounts:pending_update' x.id %}">
                    <button type="button" class="btn btn-success">Update Request</button>
                </a>&nbsp; 
                <a href="{% url 'accounts:procurement_delete' x.id %}">
                    <button type="button" class="btn btn-danger">Cancel Request</button>
                </a>
              </td>
          </tr>

          {% elif x.Status == "Rejected"%}
          <tr>
              <td>{{ x.PONo}}</td>
              <td>{{ x.Equipment }}</td>
              <td>PHP. {{ x.Budget }}</td>
              <td>{{ x.Requested_By}}</td>
              <td>{{ x.Requested_Date}}</td>
              <td>{{ x.Types_of_Procurement}}</td>
              <td>{{ x.Status}}</td>
              <td>{{ x.Comments}}</td>
              <td>{{ x.Processed_By}}</td>
              <td>
                {% if x.PPMP_Attachment %}
                    <a class="btn btn-primary"  href="{{x.PPMP_Attachment.url}}"  target="_blank">Review PPMP</a>
                {% endif %}
                <a href="{% url 'accounts:pending_update' x.id %}">
                    <button type="button" class="btn btn-success">Resubmit Request</button>
                </a>&nbsp; 
                <a href="{% url 'accounts:procurement_delete' x.id %}">
                    <button type="button" class="btn btn-danger">Cancel Request</button>
                </a>
              </td>
          </tr>

        {% elif x.Status == "Resubmission"%}
          <tr>
              <td>{{ x.PONo}}</td>
              <td>{{ x.Equipment }}</td>
              <td>PHP. {{ x.Budget }}</td>
              <td>{{ x.Requested_By}}</td>
              <td>{{ x.Requested_Date}}</td>
              <td>{{ x.Types_of_Procurement}}</td>
              <td>{{ x.Status}}</td>
              <td>{{ x.Comments}}</td>
              <td>{{ x.Processed_By}}</td>
              <td>
                {% if x.PPMP_Attachment %}
                    <a href="{{x.PPMP_Attachment.url}}" class="btn btn-primary">Review PPMP</a>
                {% endif %}
                <a href="{% url 'accounts:procurement_edit' x.id %}">
                    <button type="button" class="btn btn-success">Resubmit Request</button>
                </a>&nbsp; 
                <a href="{% url 'accounts:procurement_delete' x.id %}">
                    <button type="button" class="btn btn-danger">Cancel Request</button>
                </a>
              </td>
          </tr>
          {% endif %}
          {% endfor %}
      </tbody>  
    </table>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <!-- DATATABLE -->
    <script src="{%static '/js/jquery-3.1.1.min.js' %}"/></script>
    <script src="{%static '/js/bootstrap.min.js' %}"/></script>
    <script src="{%static '/js/bootstrap-datatables.min.js' %}"/></script>
    <script src="{%static '/js/datatables.min.js' %}"/></script>
    <script src="{%static '/js/bootstrap-table.min.js' %}"/></script>
    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        } );
    </script>
  </body>
</html>